Added shimmer animation
oss2019/instigo-android pull request #24
Opened 2019-06-29 15:49 UTC by rob729

Fixes #17 
Added Shimmer animation in mess, complaint status, resources activity.

2019-06-29 15:50 UTC, rob729 commented
@sonusourav Review this PR.

2019-06-30 04:56 UTC, sonusourav commented
Make a common template for all shimmer layout something similar to below one and use this in every recycler view.
![Shimmer-Feed-Demo](https://user-images.githubusercontent.com/34706326/60392430-0cf2ac80-9b20-11e9-8ea1-c065e50161dd.jpg)
# Why?
Because something like this happens --> Course list is empty.
![WhatsApp Image 2019-06-30 at 10 12 44 AM](https://user-images.githubusercontent.com/34706326/60392479-3f50d980-9b21-11e9-87b6-2325ef42386e.jpeg)

And anyway displaying item layout does not look good also.
Also, there are some redundant lines of progress dialog left like their declarations. Find and remove them.

2019-06-30 04:59 UTC, sonusourav commented
Reformat code before pushing

2019-06-30 09:26 UTC, rob729 commented
@sonusourav I have done the requested changes.

2019-06-30 14:18 UTC, sonusourav commented
@rob729 Could you please squash your commits and make a single commit.

2019-06-30 14:26 UTC, sonusourav commented
Also, some used imports are present. Reformat your code as shown in picture.
Right click on any file to reformat. Reformat removes your unused import, formats your spacing and indentation and does many other thing.
![reformat](https://user-images.githubusercontent.com/34706326/60397989-f3c61c00-9b70-11e9-8013-30063a716cf5.JPG)

2019-06-30 14:42 UTC, sonusourav requested changes

2019-06-30 14:42 UTC, sonusourav commented on app/src/main/res/values/colors.xml
> +    <color name="background">#dddddd</color>
Give a proper name to this color, not just background. The name should be relevant to what is its use. Give something like placeholder_back_color or common name of the color ( if any).

2019-06-30 14:42 UTC, sonusourav commented on app/src/main/res/layout/fragment_feedback.xml
> +
Do not add extra lines. Remove everywhere wherever extra lines are present.

2019-06-30 15:32 UTC, rob729 commented
@sonusourav I have done the requested changes.

2019-06-30 16:32 UTC, merged