Support Notifications on Oreo and above - Fixes #34
oss2019/instigo-android pull request #36
Opened 2019-10-02 07:53 UTC by kushsaini10

- Created Notification Channel for Alarms
- Applied Channel Id while building a notification

2019-10-02 08:07 UTC, kushsaini10 commented
@sonusourav Please review this and let me know if any changes are required.

2019-10-02 18:02 UTC, sonusourav requested changes

2019-10-02 18:02 UTC, sonusourav commented on app/src/main/res/values/strings.xml
> +
You can remove these unnecessary comments

2019-10-03 19:21 UTC, kushsaini10 commented on app/src/main/res/values/strings.xml
> +
Updated.

2019-10-05 08:12 UTC, sonusourav approved these changes

2019-10-05 08:12 UTC, merged