Council branch
oss2019/instigo-android pull request #40
Opened 2020-05-31 14:13 UTC by prateekcode

CouncilLayout Layout has been fixed.
I have used Recyclerview to do this.

2020-05-31 14:29 UTC, sonusourav requested changes
Compress the images before pushing. Use [this](https://www.iloveimg.com/resize-image)

2020-05-31 14:29 UTC, sonusourav commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Use JDK_1_8 only.

2020-05-31 14:29 UTC, sonusourav commented on app/src/main/java/com/iitdh/sonusourav/instigo/Council/CouncilActivity.java
> +
Remove this extra line.

2020-05-31 14:29 UTC, sonusourav commented on app/src/main/java/com/iitdh/sonusourav/instigo/Council/CouncilActivity.java
> +
Remove this line also and similarly in other places.

2020-05-31 14:29 UTC, sonusourav commented on app/src/main/java/com/iitdh/sonusourav/instigo/Council/CouncilRecyclerAdapter.java
> +
Run Optimise the imports option in android studio.

2020-05-31 14:29 UTC, sonusourav commented on app/src/main/java/com/iitdh/sonusourav/instigo/Council/CouncilRecyclerAdapter.java
> +        this.mCouncilName = mCouncilName;
Don't use `Hungarian notation`. [Reason](https://stackoverflow.com/questions/111933/why-shouldnt-i-use-hungarian-notation)

2020-05-31 14:29 UTC, sonusourav commented on app/src/main/java/com/iitdh/sonusourav/instigo/Council/CouncilRecyclerAdapter.java
> +        View view = inflater.inflate(R.layout.council_single_item, parent, false);
These two lines can be made into one. Don't create unnecessary variables.

2020-05-31 14:29 UTC, sonusourav commented on app/src/main/res/layout/council_single_item.xml
> +
Remove extra lines here also.

2020-05-31 15:08 UTC, prateekcode commented
As after your suggestion I fixed the following issues:
1. Compressed Image
2. Used JDK 1_8
3. Removed all extra lines
4. Optimized Imports
5. Not using Hungarian Notation
6. Not using unnecessary variables

2020-06-01 02:20 UTC, sonusourav approved these changes

2020-06-01 02:21 UTC, merged